name: My VOI 2021
url: https://hasakiyuu.github.io/
description: The diary of my VOI 2021

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
